### ISSUE TITLE
Сделать watch-режим

### ISSUE THREAD

**Issue by trikadin** [SnakeskinTpl/gulp-snakeskin#1]
При включенной опции строить граф зависимостей для *.ss файлов, и если какая-то зависимость обновилась -- то зависимые файлы так же должны быть обновлены (и отданы в поток).

Хотя, конечно, это сильное усложнение логики.

**Comment by kobezzza** [comment]
А зачем? Мне кажется можно тупо при изменении любого файла перекомпиливать всё, а для больших проектов всё равно юзать вебпак.

**Comment by trikadin** [comment]
Потому что серверные шаблоны, на клиенте юзаться не будут. Клеить сверху вебпак только ради удобной сборки SS -- это не гуд решение.

**Comment by kobezzza** [comment]
А что мешает просто запустить CLI? Через тот же gulp-run.

**Comment by trikadin** [comment]
Ну, а зачем тогда вообще gulp-snakeskin нужен?)

**Comment by kobezzza** [comment]
> Ну, а зачем тогда вообще gulp-snakeskin нужен?)

Ну, можно удалить.

**Comment by trikadin** [comment]
Лол. Да не. Сделать watch-режим в нём не так уж и сложно, как мне представляется. Я уже обдумал эту идею.

**Comment by trikadin** [comment]
Всё равно сейчас будем новую версию SS выпускать, не грех обновить плагины. Ты, кстати, какие версии ноды поддерживать планируешь?

**Comment by kobezzza** [comment]
> Ты, кстати, какие версии ноды поддерживать планируешь?

0.12+

> Сделать watch-режим в нём не так уж и сложно, как мне представляется.

Правильнее тогда его сделать в самом СС, а в плагины просто добавить вызовы.

**Comment by trikadin** [comment]
Ну, у вебпака, например, всё равно отдельная логика будет -- там не надо самому вотчить файлы, просто сказать, от каких зависишь. 

И вообще, не очень понимаю. Добавить вотчинг в api SS для ноды -- нафига? Он нужен только при сборке. Сборка, в основном -- это галп или вебпак. С вебпаком проблем вообще нет. С галпом есть, но её можно решить, и пихать новый, не очень нужный функционал в SS для этого -- зачем?..

> 0.12+

М-м... Для чего?

**Comment by kobezzza** [comment]
> М-м... Для чего?

Я против повышения версии ноды ради повышения версия ноды. СС работает с 0.12, значит плагины также должны с ней работать.

**Comment by kobezzza** [comment]
> С галпом 

Раз в галп добавим, то и в грант придётся как минимум.

**Comment by trikadin** [comment]
> СС работает с 0.12

Собственно, я и спрашиваю -- зачем SS поддерживает ноду < 4.2 (которая LTS)?

**Comment by trikadin** [comment]
> Раз в галп добавим, то и в грант придётся как минимум.

Ну, если кому понадобится -- добавим.

**Comment by kobezzza** [comment]
> Собственно, я и спрашиваю -- зачем SS поддерживает ноду < 4.2 (которая LTS)?

Потому что транслятор должен работать в окружении VM с ES5 (для live трансляции и запуска внутри Java через Nashorn).

**Comment by trikadin** [comment]
Да, точно, с Nashorn понял. А с live-трансляцией что?

**Comment by kobezzza** [comment]
> А с live-трансляцией что?

Ну чтобы в браузере работало, там поддержка ES6 тоже не фонтан пока.

**Comment by trikadin** [comment]
> Ну чтобы в браузере работало, там поддержка ES6 тоже не фонтан пока.

А, ну да.

**Comment by kobezzza** [comment]
@trikadin пинг. Таску можно закрывать?
